defaults:
  - _self_
  - optim: adam
  - dataset: ???
  - model: ???

seed: 0  # General seed used for almost everything
datasplit_seed: 0  # Seed used for splitting datasets without public split

num_train_per_class: 20  # If a split for a dataset is generated, how many nodes per class should be used for training
public_split: true  # Whether to use the public split if available, or the fixed num_train_per_class split if not available. Set this to false if you want to use another type of split.
proportional_split: false  # Whether to create training splits, in which the frequency of class labels is proportional to their overall frequency
degree_split: false  # Whether to create a data split based on the degree distribution
part_val: 0.15  # Only used with proportional split: how many nodes should be used for validation
part_test: 0.8  # Only used with proportional split: how many nodes should be used for testing. Rest is used for training.

cuda: ???  # Identifier of a GPU (0, 1, ...) or 'cpu'

n_epochs: 500  # Maximal training epochs
early_stopping: true  # Whether to use early stopping
patience: 40  # After how many epochs without val_loss improvement to stop training

store_activations: false  # Whether to store activations of trained models on disk
data_root: ???  # CHANGE: this should be an absolute path to the data subdirectory